boardgames_index:
    path: /boardgames
    controller: App\Controller\BoardgamesController::index

innovation_index:
    path: /boardgames/innovation
    controller: App\Controller\InnovationController::index
        
innovation_game_join:
    path: /boardgames/game/{gameId}/join
    controller: App\Controller\InnovationController::joinGame
    requirements:
        gameId: \d+
innovation_game_leave:
    path: /boardgames/game/{gameId}/leave
    controller: App\Controller\InnovationController::leaveGame
    requirements:
        gameId: \d+
innovation_game_reinit:
    path: /boardgames/game/{gameId}/reinitialiser
    controller: App\Controller\InnovationController::reinitGame
    requirements:
        gameId: \d+
innovation_game_show:
    path: /boardgames/innovation/{gameId}
    controller: App\Controller\InnovationController::showGame
    requirements:
        gameId: \d+
innovation_game_action_reset:
    path: /boardgames/innovation/{gameId}/action/{actionId}/reset
    controller: App\Controller\InnovationController::resetAction
    requirements:
        gameId: \d+
        actionId: \d+
